# Generated by Django 5.2.4 on 2025-09-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(choices=[('petrol', 'PETROL'), ('diesel', 'DIESEL'), ('ev', 'EV')], max_length=100)),
                ('seat_capacity', models.CharField(choices=[(5, 5), (7, 7)], max_length=100)),
                ('transmission_type', models.CharField(choices=[('manual', 'MANUAL'), ('automatic', 'AUTOMATIC')], max_length=100)),
                ('total_km_driven', models.IntegerField()),
                ('amminities', models.TextField()),
                ('bootspace', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('carimg', models.ImageField(blank=True, null=True, upload_to='carimg/')),
            ],
        ),
    ]
