# Generated by Django 5.2.4 on 2025-09-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalcars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carz',
            name='seat_capacity',
            field=models.CharField(choices=[(5, '5'), (7, '7')], max_length=100),
        ),
    ]
