# Generated by Django 5.2.4 on 2025-09-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalcars', '0003_alter_carz_seat_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='carz',
            name='mileage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
